apiVersion: apps/v1
kind: Deployment
metadata:
  name: req-verifier
  labels:
    app: req-verifier
spec:
  selector:
    matchLabels:
      app: req-verifier
  template:
    metadata:
      labels:
        app: req-verifier
    spec:
      serviceAccountName: req-verifier
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: req-verifier-container
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: zikadocker1991/verifier:v4
        ports:
        - containerPort: 5001
        env:
        - name: SERVER_PORT
          value: "5001"
        - name: SERVICE_DOMAIN
          value: "http://frontend.default.svc.cluster.local:80/"
        - name: SERVER_TYPE
          value: "fastapi"
        args: ["req", "0"]
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          httpGet:
            path: /healthz
            port: 5001
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          httpGet:
            path: /healthz
            port: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: req-verifier
  labels:
    app: req-verifier
spec:
  type: ClusterIP
  selector:
    app: req-verifier
  ports:
  - name: http
    port: 5001
    targetPort: 5001
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: req-verifier

