Fatal error: exception Division_by_zero
WARNING: AVG applied on empty relation at time point 1, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: AVG applied on empty relation at time point 2, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: MIN applied on empty relation at time point 1, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: MIN applied on empty relation at time point 2, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: MAX applied on empty relation at time point 1, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: MAX applied on empty relation at time point 2, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: MED applied on empty relation at time point 1, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: MED applied on empty relation at time point 2, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: AVG applied on empty relation at time point 0, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: AVG applied on empty relation at time point 2, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: MIN applied on empty relation at time point 0, timestamp 0.! Resulting value is inf, by (our) convention.
WARNING: MIN applied on empty relation at time point 2, timestamp 0.! Resulting value is inf, by (our) convention.
WARNING: MAX applied on empty relation at time point 0, timestamp 0.! Resulting value is -inf, by (our) convention.
WARNING: MAX applied on empty relation at time point 2, timestamp 0.! Resulting value is -inf, by (our) convention.
WARNING: MED applied on empty relation at time point 0, timestamp 0.! Resulting value is 0, by (our) convention.
WARNING: MED applied on empty relation at time point 2, timestamp 0.! Resulting value is 0, by (our) convention.
Fatal error: exception Failure("[Rewriting.type_check_term] Type check error on term x: expected type String, actual type (Num t3) =>  t3")
Fatal error: exception Failure("[Rewriting.type_check_term] Type check error on term x: expected type String, actual type (Num t3) =>  t3")
WARNING: MIN applied on empty relation at time point 0, timestamp 0.! Resulting value is "", by (our) convention.
WARNING: MIN applied on empty relation at time point 1, timestamp 0.! Resulting value is "", by (our) convention.
WARNING: MAX applied on empty relation at time point 0, timestamp 0.! Resulting value is "", by (our) convention.
WARNING: MAX applied on empty relation at time point 1, timestamp 0.! Resulting value is "", by (our) convention.
Fatal error: exception Failure("[Rewriting.type_check_term] Type check error on term x: expected type String, actual type (Num t3) =>  t3")
Fatal error: exception Failure("[Rewriting.type_check_term] Type check error on term x: expected type String, actual type (Num t3) =>  t3")
Fatal error: exception Failure("[Rewriting.type_check_term] Type check error on term x: expected type String, actual type (Num t3) =>  t3")
Fatal error: exception Failure("[Rewriting.type_check_term] Type check error on term x: expected type String, actual type (Num t3) =>  t3")
